### PR TITLE
Ensure imbarcode conforms to USPS reference tests

### PR DESCRIPTION
**Pull request by gws**
I've added the USPS reference tests for conforming implementations (available on [ribbs.usps.gov](https://ribbs.usps.gov/onecodesolution/download.cfm)) and made a small change to the library which will check that the barcode ID conforms to [section 2.1.3 of the specification](https://ribbs.usps.gov/intelligentmail_mailpieces/documents/tech_guides/USPSB3200IntelligentMailBarcode4State.pdf) in order to avoid generating invalid barcodes.

### CODE REVIEW

**Comment by cap10morgan** [comment]
@gws If it's alright with you, I'd like to wait on merging this until we get to the acceptance testing phase of injecting USPS scan events and verifying that they do what we expect. Then we can run those tests on this branch of usps-processor and verify that nothing breaks (or maybe even that tests that fail on master are fixed by this branch). Sound OK?

**Comment by gws** [comment]
Oh sure, that sounds good.

It's worth nothing that the changes here would potentially impact barcode *generation*, so rather than having an impact on`usps-processor` it might rather have consequences for mailing label creation.

**Comment by cap10morgan** [comment]
@tie-rack If you remember anything about this work (it's been awhile), do you have thoughts or questions on this PR?

**Comment by tie-rack** [comment]
It looks like this change will only prevent us from generating a certain class of invalid barcodes, but won't change valid ones at all. So it looks pretty safe to me!

**Pull request merged**
